### ISSUE TITLE
Failed install on Duet 3 MB6HC with RRF 3.4.5

### ISSUE THREAD

**Issue by Garth-42** [LoicGRENON/DSF_ExecOnMcode_Plugin#2]
Hello,
I get the following error when I try to install the plugin on my Duet3 in SBC mode. dsf-python is also installed on the RPI. Pip3 is recognized in the terminal when I enter "pip3".

<img width="1512" alt="Screenshot 2022-12-28 at 9 33 47 PM" src="https://user-images.githubusercontent.com/12802614/209900410-28611e43-0c15-4997-a21a-be92394fca16.png">

Here is an output of M122:

M122
=== Diagnostics ===
RepRapFirmware for Duet 3 MB6HC version 3.4.5 (2022-11-30 19:35:23) running on Duet 3 MB6HC v1.01 (SBC mode)
Board ID: 08DJM-956BA-NA3TJ-6JTDA-3S06M-9U8GS
Used output buffers: 1 of 40 (13 max)
=== RTOS ===
Static ram: 152760
Dynamic ram: 67548 of which 204 recycled
Never used RAM 130160, free system stack 200 words
Tasks: SBC(ready,0.5%,446) HEAT(notifyWait,0.0%,322) Move(notifyWait,0.0%,351) CanReceiv(notifyWait,0.0%,774) CanSender(notifyWait,0.0%,336) CanClock(delaying,0.0%,339) TMC(notifyWait,7.6%,91) MAIN(running,91.8%,923) IDLE(ready,0.0%,30), total 100.0%
Owned mutexes: HTTP(MAIN)
=== Platform ===
Last reset 01:16:51 ago, cause: software
Last software reset at 2022-05-29 08:42, reason: User, GCodes spinning, available RAM 132740, slot 1
Software reset code 0x0003 HFSR 0x00000000 CFSR 0x00000000 ICSR 0x00400000 BFAR 0x00000000 SP 0x00000000 Task SBC Freestk 0 n/a
Error status: 0x00
Step timer max interval 134
MCU temperature: min 25.1, current 27.1, max 27.2
Supply voltage: min 24.0, current 24.0, max 24.1, under voltage events: 0, over voltage events: 0, power good: yes
12V rail voltage: min 12.1, current 12.2, max 12.2, under voltage events: 0
Heap OK, handles allocated/used 0/0, heap memory allocated/used/recyclable 0/0/0, gc cycles 0
Events: 0 queued, 0 completed
Driver 0: standstill, SG min 0, mspos 8, reads 15144, writes 15 timeouts 0
Driver 1: standstill, SG min 0, mspos 8, reads 15145, writes 15 timeouts 0
Driver 2: standstill, SG min 0, mspos 8, reads 15144, writes 16 timeouts 0
Driver 3: standstill, SG min 0, mspos 8, reads 15145, writes 15 timeouts 0
Driver 4: standstill, SG min 0, mspos 8, reads 15145, writes 15 timeouts 0
Driver 5: standstill, SG min 0, mspos 8, reads 15145, writes 15 timeouts 0
Date/time: 2022-12-28 21:41:46
Slowest loop: 1.48ms; fastest: 0.04ms
=== Storage ===
Free file entries: 10
SD card 0 not detected, interface speed: 37.5MBytes/sec
SD card longest read time 0.0ms, write time 0.0ms, max retries 0
=== Move ===
DMs created 125, segments created 0, maxWait 0ms, bed compensation in use: none, comp offset 0.000
=== MainDDARing ===
Scheduled moves 0, completed 0, hiccups 0, stepErrors 0, LaErrors 0, Underruns [0, 0, 0], CDDA state -1
=== AuxDDARing ===
Scheduled moves 0, completed 0, hiccups 0, stepErrors 0, LaErrors 0, Underruns [0, 0, 0], CDDA state -1
=== Heat ===
Bed heaters 0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1, chamber heaters -1 -1 -1 -1, ordering errs 0
=== GCodes ===
Segments left: 0
Movement lock held by null
HTTP* is doing "M122" in state(s) 0
Telnet is idle in state(s) 0
File is idle in state(s) 0
USB is idle in state(s) 0
Aux is idle in state(s) 0
Trigger* is idle in state(s) 0
Queue is idle in state(s) 0
LCD is idle in state(s) 0
SBC* is idle in state(s) 0
Daemon is idle in state(s) 0
Aux2 is idle in state(s) 0
Autopause is idle in state(s) 0
Code queue is empty
=== CAN ===
Messages queued 41489, received 36956, lost 0, boc 0
Longest wait 1ms for reply type 6042, peak Tx sync delay 386, free buffers 50 (min 49), ts 23058/23057/0
Tx timeouts 0,0,0,0,0,0
=== SBC interface ===
Transfer state: 5, failed transfers: 0, checksum errors: 0
RX/TX seq numbers: 23547/23547
SPI underruns 0, overruns 0
State: 5, disconnects: 5, timeouts: 5 total, 5 by SBC, IAP RAM available 0x2ad20
Buffer RX/TX: 0/0-0, open files: 0
=== Duet Control Server ===
Duet Control Server v3.4.5
Code buffer space: 4096
Configured SPI speed: 8000000Hz, TfrRdy pin glitches: 0
Full transfers per second: 38.22, max time between full transfers: 66.3ms, max pin wait times: 60.9ms/3.9ms
Codes per second: 0.00
Maximum length of RX/TX data transfers: 3195/64

Let me know if I can help with resolving this issue with any more information.

**Comment by LoicGRENON** [comment]
Hello
Please use the Duet forum for support : https://forum.duet3d.com/category/41/plugins-for-dwc-and-dsf

**Comment by Garth-42** [comment]
This issue has been fixed via the forum. See this thread for more details: [https://forum.duet3d.com/topic/29783/execonmcode/64](https://forum.duet3d.com/topic/29783/execonmcode/64)
